# Generated by Django 6.0.5 on 2026-05-23 06:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(db_index=True,
                 max_length=10, unique=True, verbose_name='کد ملی')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(
                    max_length=100, verbose_name='نام خانوادگی')),
                ('total_presence', models.CharField(
                    max_length=10, verbose_name='مجموع حضور')),
                ('reduction_work', models.CharField(
                    max_length=10, verbose_name='کسر کار')),
                ('hourly_leave', models.CharField(
                    max_length=10, verbose_name='مرخصی ساعتی')),
                ('hourly_mission', models.CharField(
                    max_length=10, verbose_name='ماموریت ساعتی')),
                ('total_overtime', models.CharField(
                    max_length=10, verbose_name='اضافه کار')),
                ('annual_leave_days', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(
                    0), django.core.validators.MaxValueValidator(31)], verbose_name='مرخصی استحقاقی (روز)')),
                ('sick_leave_days', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(
                    0), django.core.validators.MaxValueValidator(31)], verbose_name='مرخصی استعلاجی (روز)')),
                ('daily_mission_days', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(
                    0), django.core.validators.MaxValueValidator(31)], verbose_name='ماموریت روزانه (روز)')),
                ('total_shift_hours', models.PositiveSmallIntegerField(
                    verbose_name='مجموع ساعت شیفت')),
                ('updated_at', models.DateTimeField(
                    auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'گزارش پرسنل',
                'verbose_name_plural': 'گزارش\u200cهای پرسنل',
            },
        ),
        migrations.CreateModel(
            name='StaffContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(db_index=True,
                 max_length=10, unique=True, verbose_name='کد ملی')),
                ('phone_number', models.CharField(max_length=11,
                 unique=True, verbose_name='شماره موبایل')),
            ],
            options={
                'verbose_name': 'اطلاعات تماس',
                'verbose_name_plural': 'اطلاعات تماس پرسنل',
            },
        ),
    ]
