# Generated by Django 6.0.5 on 2026-05-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='staffcontact',
            index=models.Index(
                fields=[
                    'national_id',
                    'phone_number'],
                name='reports_sta_nationa_3dd02e_idx'),
        ),
    ]
