# Generated by Django 6.0.5 on 2026-06-06 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_staffcontact_reports_sta_nationa_3dd02e_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeereport',
            options={'verbose_name': 'گزارش عملکرد پرسنل', 'verbose_name_plural': 'گزارش\u200c عملکرد پرسنل'},
        ),
        migrations.AlterModelOptions(
            name='staffcontact',
            options={'verbose_name': 'اطلاعات تماس ', 'verbose_name_plural': 'اطلاعات تماس پرسنل'},
        ),
    ]
