"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
env = environ.Env(
    DEBUG=(bool, False)
)

environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = True
SECRET_KEY = 'django-insecure-kukls%)ef5eu3xu68m#r)ep!qc)q+n#oj%y*mv&26e54!0hr&_'
BALE_BOT_API_KEY = 'CHANGE-ME'
# DEBUG = env("DEBUG")
# SECRET_KEY = env("SECRET_KEY")
# BALE_BOT_API_KEY = env("BALE_BOT_API_KEY")

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    "unfold", 
    "unfold.contrib.filters", # optional
    "unfold.contrib.forms",   # optional
    "unfold.contrib.inlines", # optional
    "unfold.contrib.import_export",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 3rd party
    'import_export',
    # 'admin_tools',
    # 'admin_tools.dashboard',
    # 'admin_tools.menu',
    # apps
    'reports',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_TZ = True

LANGUAGE_CODE = 'fa-ir'
USE_I18N = True
USE_L10N = True
USE_TZ = True

DJANGO_ADMIN_PERSIAN_FONTS_NAME = 'vazir'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
# The directory where collectstatic will gather all static files

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATIC_URL = 'static/'


# ─── Unfold Settings ───────────────────────────────────────────────
UNFOLD = {
    "SITE_TITLE": "پنل بله",
    "SITE_HEADER": "پنل توزیع داده‌های بات بله",
    "SITE_URL": "/",
    
    # Show the Django admin's default sidebar
    "SHOW_HISTORY": True,  
    "SHOW_VIEW_ON_SITE": True,
    
    # ── Fonts ──
    # Unfold uses modern system fonts by default that handle Persian well.
    # If you want Vazirmatn specifically, add a CDN link here:
    "EXTRA_STYLES": [
        "https://cdn.jsdelivr.net/gh/rastikerdar/vazirmatn@v33.003/Vazirmatn-font-face.css",
    ],
    
    # ── Sidebar ──
    "SIDEBAR": {
        # "show_search": True,
        "navigation": [
            {
                "title": "اطلاعات کارمندان",
                "separator": True,
                "items": [
                    {
                        "title": "بارگذاری عملکرد ماهانه",
                        "icon": "analytics",
                        "link": "/admin/reports/employeereport/",
                    },
                    {
                        "title": "دفترچه تلفن و احراز هویت", 
                        "icon": "contacts",
                        "link": "/admin/reports/staffcontact/",
                    },
                ],
            },
        ],
    },
    
    # ── Import-Export compatibility ──
    "TABS": [],
}
